import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { OrbitControls, Stats, Text } from "@react-three/drei";
import { useState, useEffect, useRef, createContext, Fragment } from 'react'

import Box from '../components/Box'

const camContext = createContext()
function Controls({ children }) {
  const { gl, camera } = useThree()
  const api = useState(true)
  return (
    <Fragment>
      <OrbitControls enableRotate={false} args={[camera, gl.domElement]} enableDamping enabled={api[0]} />
      <camContext.Provider value={api}>{children}</camContext.Provider>
    </Fragment>
  )
}

export default function Home() {  

  // Hover logic
  const [hovered, setHovered] = useState(false);
  useEffect(() => {
    document.body.style.cursor = hovered ? 'pointer' : 'auto'
  }, [hovered])

  return (
    <div className={styles.container}>
      <Head>
        <title>Network</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Canvas camera={{fov: 65}} ><Controls>
          <color attach="background" args={['black']} />
          <ambientLight intensity={0.1} />
          <directionalLight color="white" position={[10, 10, 10]} />
          
          <Text
            position={[0, 0.8, 3]}
            scale={[1.3, 1.3, 1.3]}
            color="white" // default
            anchorX="center" // default
            anchorY="middle" // default
          >
            Web Works
          </Text>
          <Box position={[0, -0.2, 3]} args={[1, 1.3, 0.2]} amplitude={0.0005} setHovered={setHovered}/>
        </Controls></Canvas>
      </main>

    </div>
  )
}
